version: '3.8'
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: platon
      MINIO_ROOT_PASSWORD: fancaran
    command: server --console-address ":9001" /data
    networks:
      - shared-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared-network


  data-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    environment:
      DB_HOST: db
      MINIO_HOST: minio
    networks:
      - shared-network

volumes:
  minio_storage: {}
  db: {}
networks:
  shared-network:
    external: true
